# Generated by Django 2.1.2 on 2018-10-03 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled', max_length=30)),
                ('total_budgets', models.FloatField()),
                ('remaining_budget', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('choices', models.CharField(choices=[('withdrawal', 'WITHDRAWAL'), ('deposit', 'DEPOSIT')], max_length=150)),
                ('amount', models.FloatField()),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='budgets.Budget')),
            ],
        ),
        migrations.RemoveField(
            model_name='budgets',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='budget',
        ),
        migrations.DeleteModel(
            name='Budgets',
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
